package com.bootcamp.bootcampecomproject.enums;

public enum  ToStatus {
    CANCELLED,
    ORDER_CONFIRMED,
    ORDER_REJECTED,
    REFUND_INITIATED,
    ORDER_SHIPPED,
    DELIVERED,
    RETURN_REQUESTED,
    CLOSED,
    RETURN_REJECTED,
    RETURN_APPROVED,
    PICK_UP_INITIATED,
    PICK_UP_COMPLETED,
    REFUND_COMPLETED
}
